# Configuration for the golang-gci utility.
#
# There are some disabled linters that enabling them would help us improve our
# code's quality. However, enabling them requires some refactoring work in the
# codebase.
#
# The disabled linters are tagged as follows —order matters—:
#
# - Must have: they include very important and insightful checks that will
#              significantly improve the codebase's quality, resiliency,
#              security and maintainability.
# - Nice to have: they might improve some aspects of the code, but they are
#                 not as important.
# - Untagged: they might just be cosmetic changes or linters that would end up
#             making the development experience way too painful.

version: "2"
linters:
  default: all
  disable:
    - canonicalheader # nice to have.
    - containedctx # must have.
    - cyclop
    - decorder # nice to have.
    - depguard
    - dupl
    - err113 # must have.
    - errcheck # must have.
    - errchkjson # must have.
    - errname # must have.
    - errorlint # must have.
    - exhaustruct
    - forbidigo
    - funcorder
    - funlen
    - gochecknoglobals # must have.
    - gochecknoinits # must have.
    - gocognit
    - goconst # nice to have.
    - gocritic # must have.
    - gocyclo
    - godot # nice to have.
    - godox # must have.
    - gosec # must have.
    - inamedparam # nice to have.
    - interfacebloat
    - intrange # nice to have.
    - ireturn # must have.
    - lll
    - maintidx
    - makezero # nice to have.
    - mirror # must have.
    - mnd
    - musttag # nice to have.
    - nakedret
    - nestif
    - nilerr # must have.
    - nilnesserr # nice to have.
    - nilnil # must have.
    - nlreturn # nice to have.
    - nonamedreturns # nice to have.
    - nosprintfhostport # must to have.
    - paralleltest # nice to have.
    - perfsprint # nice to have.
    - prealloc # nice to have.
    - recvcheck # nice ot have.
    - revive # nice to have.
    - staticcheck # must have.
    - tagalign # nice to have.
    - tagliatelle
    - testpackage
    - thelper # nice to have.
    - unconvert # nice to have.
    - unparam # nice to have.
    - usestdlibvars # nice to have.
    - usetesting # nice to have.
    - varnamelen
    - wastedassign # nice to have.
    - whitespace # nice to have.
    - wrapcheck
    - wsl # nice to have.
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - contextcheck
    - copyloopvar
    - decorder
    - dogsled
    - dupword
    - durationcheck
    - exhaustive
    - exptostd
    - fatcontext
    - forcetypeassert
    - ginkgolinter
    - gocheckcompilerdirectives
    - gochecksumtype
    - goheader
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosmopolitan
    - govet
    - grouper
    - iface
    - importas
    - ineffassign
    - loggercheck
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - predeclared
    - promlinter
    - protogetter
    - reassign
    - rowserrcheck
    - sloglint
    - spancheck
    - sqlclosecheck
    - testableexamples
    - testifylint
    - tparallel
    - unused
    - zerologlint
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - forcetypeassert
        path: (.+)_test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
