package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.72

import (
	"context"
	"encoding/json"
	"strconv"

	"github.com/RedHatInsights/sources-api-go/dao"
	"github.com/RedHatInsights/sources-api-go/graph/generated"
	generated_model "github.com/RedHatInsights/sources-api-go/graph/model"
	"github.com/RedHatInsights/sources-api-go/model"
	"github.com/RedHatInsights/sources-api-go/util"
)

// ID is the resolver for the id field.
func (r *applicationResolver) ID(ctx context.Context, obj *model.Application) (string, error) {
	return strconv.Itoa(int(obj.ID)), nil
}

// ApplicationTypeID is the resolver for the application_type_id field.
func (r *applicationResolver) ApplicationTypeID(ctx context.Context, obj *model.Application) (string, error) {
	return strconv.Itoa(int(obj.ApplicationTypeID)), nil
}

// Extra is the resolver for the extra field.
func (r *applicationResolver) Extra(ctx context.Context, obj *model.Application) (any, error) {
	if obj.Extra == nil {
		return nil, nil
	}

	m := make(map[string]interface{})
	err := json.Unmarshal(obj.Extra, &m)
	return m, err
}

// Authentications is the resolver for the authentications field.
func (r *applicationResolver) Authentications(ctx context.Context, obj *model.Application) ([]*model.Authentication, error) {
	err := getRequestDataFromCtx(ctx).EnsureAuthenticationsAreLoaded()
	if err != nil {
		return nil, err
	}

	auths := authenticationsFromCtx(ctx, "Application", obj.ID)
	out := make([]*model.Authentication, len(auths))
	for i := range auths {
		out[i] = &auths[i]
	}
	return out, err
}

// TenantID is the resolver for the tenant_id field.
func (r *applicationResolver) TenantID(ctx context.Context, obj *model.Application) (string, error) {
	return strconv.Itoa(int(*tenantIdFromCtx(ctx))), nil
}

// ID is the resolver for the id field.
func (r *applicationTypeResolver) ID(ctx context.Context, obj *model.ApplicationType) (string, error) {
	return strconv.FormatInt(obj.Id, 10), nil
}

// DependentApplications is the resolver for the dependent_applications field.
func (r *applicationTypeResolver) DependentApplications(ctx context.Context, obj *model.ApplicationType) (any, error) {
	return obj.DependentApplications, nil
}

// SupportedSourceTypes is the resolver for the supported_source_types field.
func (r *applicationTypeResolver) SupportedSourceTypes(ctx context.Context, obj *model.ApplicationType) (any, error) {
	return obj.SupportedSourceTypes, nil
}

// SupportedAuthenticationTypes is the resolver for the supported_authentication_types field.
func (r *applicationTypeResolver) SupportedAuthenticationTypes(ctx context.Context, obj *model.ApplicationType) (any, error) {
	return obj.SupportedAuthenticationTypes, nil
}

// Sources is the resolver for the sources field.
func (r *applicationTypeResolver) Sources(ctx context.Context, obj *model.ApplicationType) ([]*model.Source, error) {
	srces, _, err := dao.GetSourceDao(&dao.RequestParams{TenantID: tenantIdFromCtx(ctx), UserID: userIdFromCtx(ctx)}).SubCollectionList(model.ApplicationType{Id: obj.Id}, 500, 0, []util.Filter{})

	out := make([]*model.Source, len(srces))
	for i := range srces {
		out[i] = &srces[i]
	}

	return out, err
}

// ID is the resolver for the id field.
func (r *authenticationResolver) ID(ctx context.Context, obj *model.Authentication) (string, error) {
	return obj.GetID(), nil
}

// ResourceID is the resolver for the resource_id field.
func (r *authenticationResolver) ResourceID(ctx context.Context, obj *model.Authentication) (string, error) {
	return strconv.Itoa(int(obj.ResourceID)), nil
}

// TenantID is the resolver for the tenant_id field.
func (r *authenticationResolver) TenantID(ctx context.Context, obj *model.Authentication) (string, error) {
	return strconv.Itoa(int(*tenantIdFromCtx(ctx))), nil
}

// ID is the resolver for the id field.
func (r *endpointResolver) ID(ctx context.Context, obj *model.Endpoint) (string, error) {
	return strconv.Itoa(int(obj.ID)), nil
}

// Authentications is the resolver for the authentications field.
func (r *endpointResolver) Authentications(ctx context.Context, obj *model.Endpoint) ([]*model.Authentication, error) {
	err := getRequestDataFromCtx(ctx).EnsureAuthenticationsAreLoaded()
	if err != nil {
		return nil, err
	}

	auths := authenticationsFromCtx(ctx, "Endpoint", obj.ID)
	out := make([]*model.Authentication, len(auths))
	for i := range auths {
		out[i] = &auths[i]
	}
	return out, err
}

// TenantID is the resolver for the tenant_id field.
func (r *endpointResolver) TenantID(ctx context.Context, obj *model.Endpoint) (string, error) {
	return strconv.Itoa(int(*tenantIdFromCtx(ctx))), nil
}

// Sources is the resolver for the sources field.
func (r *queryResolver) Sources(ctx context.Context, limit *int, offset *int, sortBy []*generated_model.SortBy, filter []*generated_model.Filter) ([]*model.Source, error) {
	// default limit and offset
	if limit == nil {
		limit = new(int)
		*limit = 100
	}
	if offset == nil {
		offset = new(int)
		*offset = 0
	}

	// parse any filters passed along the request
	f := parseArgs(sortBy, filter)

	// list the sources with filters en tote!
	srces, count, err := dao.GetSourceDao(&dao.RequestParams{TenantID: tenantIdFromCtx(ctx), UserID: userIdFromCtx(ctx)}).List(*limit, *offset, f)

	sendCount(ctx, count)

	// storing the IDs of relevant sources on the request context for later subresources
	sourceIDs := make([]string, len(srces))

	// output data needs to be pointers for some reason.
	out := make([]*model.Source, len(srces))
	for i := range srces {
		out[i] = &srces[i]
		sourceIDs[i] = strconv.FormatInt(srces[i].ID, 10)
	}

	// this will unlock the source mutex and let the subresources go
	getRequestDataFromCtx(ctx).SetSourceIDs(sourceIDs)
	return out, err
}

// ApplicationTypes is the resolver for the application_types field.
func (r *queryResolver) ApplicationTypes(ctx context.Context, limit *int, offset *int, sortBy []*generated_model.SortBy, filter []*generated_model.Filter) ([]*model.ApplicationType, error) {
	// default limit and offset
	if limit == nil {
		limit = new(int)
		*limit = 100
	}
	if offset == nil {
		offset = new(int)
		*offset = 0
	}

	// parse any filters passed along the request
	f := parseArgs(sortBy, filter)
	appTypes, count, err := dao.GetApplicationTypeDao(tenantIdFromCtx(ctx)).List(*limit, *offset, f)
	sendCount(ctx, count)

	out := make([]*model.ApplicationType, len(appTypes))
	for i := range appTypes {
		out[i] = &appTypes[i]
	}
	return out, err
}

// Meta is the resolver for the meta field.
func (r *queryResolver) Meta(ctx context.Context) (*generated_model.Meta, error) {
	return &generated_model.Meta{Count: getCount(ctx)}, nil
}

// ID is the resolver for the id field.
func (r *sourceResolver) ID(ctx context.Context, obj *model.Source) (string, error) {
	return strconv.Itoa(int(obj.ID)), nil
}

// SourceTypeID is the resolver for the source_type_id field.
func (r *sourceResolver) SourceTypeID(ctx context.Context, obj *model.Source) (string, error) {
	return strconv.Itoa(int(obj.SourceTypeID)), nil
}

// Authentications is the resolver for the authentications field.
func (r *sourceResolver) Authentications(ctx context.Context, obj *model.Source) ([]*model.Authentication, error) {
	err := getRequestDataFromCtx(ctx).EnsureAuthenticationsAreLoaded()
	if err != nil {
		return nil, err
	}

	auths := authenticationsFromCtx(ctx, "Source", obj.ID)
	out := make([]*model.Authentication, len(auths))
	for i := range auths {
		out[i] = &auths[i]
	}
	return out, err
}

// Endpoints is the resolver for the endpoints field.
func (r *sourceResolver) Endpoints(ctx context.Context, obj *model.Source) ([]*model.Endpoint, error) {
	err := getRequestDataFromCtx(ctx).EnsureEndpointsAreLoaded()
	if err != nil {
		return nil, err
	}

	endpts := sourceEndpointsFromCtx(ctx, obj.ID)
	out := make([]*model.Endpoint, len(endpts))
	for i := range endpts {
		out[i] = &endpts[i]
	}

	return out, nil
}

// Applications is the resolver for the applications field.
func (r *sourceResolver) Applications(ctx context.Context, obj *model.Source) ([]*model.Application, error) {
	err := getRequestDataFromCtx(ctx).EnsureApplicationsAreLoaded()
	if err != nil {
		return nil, err
	}

	apps := sourceApplicationsFromCtx(ctx, obj.ID)
	out := make([]*model.Application, len(apps))
	for i := range apps {
		out[i] = &apps[i]
	}

	return out, nil
}

// TenantID is the resolver for the tenant_id field.
func (r *sourceResolver) TenantID(ctx context.Context, obj *model.Source) (string, error) {
	return strconv.Itoa(int(*tenantIdFromCtx(ctx))), nil
}

// Application returns generated.ApplicationResolver implementation.
func (r *Resolver) Application() generated.ApplicationResolver { return &applicationResolver{r} }

// ApplicationType returns generated.ApplicationTypeResolver implementation.
func (r *Resolver) ApplicationType() generated.ApplicationTypeResolver {
	return &applicationTypeResolver{r}
}

// Authentication returns generated.AuthenticationResolver implementation.
func (r *Resolver) Authentication() generated.AuthenticationResolver {
	return &authenticationResolver{r}
}

// Endpoint returns generated.EndpointResolver implementation.
func (r *Resolver) Endpoint() generated.EndpointResolver { return &endpointResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

// Source returns generated.SourceResolver implementation.
func (r *Resolver) Source() generated.SourceResolver { return &sourceResolver{r} }

type applicationResolver struct{ *Resolver }
type applicationTypeResolver struct{ *Resolver }
type authenticationResolver struct{ *Resolver }
type endpointResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type sourceResolver struct{ *Resolver }
