{
 "title": "Sources",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "controller",
    "label": "Controller (API)",
    "query": {
     "query": "label_values(sources_api_http_requests_total,controller)"
    }
   },
   {
    "name": "action",
    "label": "Action (API)",
    "query": {
     "query": "label_values(sources_api_http_requests_total{controller=~\"$controller\"},action)"
    }
   },
   { "name": "DatasourceRDS", "label": "Datasource (RDS)", "query": "prometheus" },
   { "name": "namespace", "label": "namespace (RDS)", "query": "sources-stage,sources-prod" }
  ]
 },
 "panels": [
  {
   "title": "General",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Pods Up",
   "type": "text",
   "gridPos": { "h": 1, "w": 4, "x": 0, "y": 1 },
   "options": { "content": "\n\n" },
   "targets": [
    {}
   ]
  },
  {
   "title": "Restarts Count",
   "type": "text",
   "gridPos": { "h": 1, "w": 4, "x": 4, "y": 1 },
   "options": { "content": "\n\n" },
   "targets": [
    {}
   ]
  },
  {
   "title": "Errors Count",
   "type": "text",
   "gridPos": { "h": 1, "w": 4, "x": 8, "y": 1 },
   "options": { "content": "\n\n" },
   "targets": [
    {}
   ]
  },
  {
   "title": "API",
   "type": "stat",
   "description": "Alert: Down for 2m",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{service=~\"sources-api-svc\"})"
    }
   ]
  },
  {
   "title": "Satellite",
   "type": "stat",
   "description": "Alert: Down for 2m",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{service=\"sources-satellite-operations\"})"
    }
   ]
  },
  {
   "title": "API",
   "type": "stat",
   "description": "Alert: > 5 [30m] for 1h",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(kube_pod_container_status_restarts_total{container=\"sources-api-svc\"}[$__range])))"
    }
   ]
  },
  {
   "title": "Satellite",
   "type": "stat",
   "description": "Alert: > 50 [5m] for 10m",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(kube_pod_container_status_restarts_total{container=\"sources-satellite-operations\"}[$__range])))"
    }
   ]
  },
  {
   "title": "API (5xx)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(api_3scale_gateway_api_status{exported_service=\"sources\", status=\"5xx\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API (4xx)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(api_3scale_gateway_api_status{exported_service=\"sources\", status=\"4xx\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SuperKey",
   "type": "stat",
   "description": "Alert: Down for 2m",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{service=\"sources-superkey-worker-svc\"})"
    }
   ]
  },
  {
   "title": "SuperKey",
   "type": "stat",
   "description": "Alert: > 5 [30m] for 1h",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(kube_pod_container_status_restarts_total{container=\"sources-superkey-worker-svc\"}[$__range])))"
    }
   ]
  },
  {
   "title": "Superkey",
   "type": "stat",
   "description": "Alert: > 50 [5m] for 10m",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "-1" }
   ]
  },
  {
   "title": "Satellite",
   "type": "stat",
   "description": "Alert: > 10 errors in 10mins for 30 minutes",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(sources_satellite_operations_errors_total[$__range])))+round(sum(increase(sources_satellite_operations_status_counter{status=\"error\"}[$__range])))"
    }
   ]
  },
  { "title": "SLI", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Latency Uptime",
   "type": "timeseries",
   "description": "Alert: Request with duration under 500ms > 95%",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(api_3scale_gateway_api_time_bucket{le=\"0500.0\", exported_service=\"sources\"}[5m])) / sum(rate(api_3scale_gateway_api_time_count{exported_service=\"sources\"}[5m]))",
     "legendFormat": "Latency Uptime"
    }
   ]
  },
  {
   "title": "Latency uptime [28d]",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(api_3scale_gateway_api_time_bucket{le=\"0500.0\", exported_service=\"sources\"}[28d])) / sum(rate(api_3scale_gateway_api_time_count{exported_service=\"sources\"}[28d]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate Uptime",
   "type": "timeseries",
   "description": "Alert: Request with duration under 500ms > 95%",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg_over_time(service:sli:status_5xx:pctl5rate5m{exported_service=\"sources\"}[5m])",
     "legendFormat": "Latency Uptime"
    }
   ]
  },
  {
   "title": "Error Rate Uptime [28d]",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(service:sli:status_5xx:pctl5rate5m{exported_service=\"sources\"}[28d])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kafka Lag",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Kafka lag",
   "type": "graph",
   "description": "Alert: > 1000 [10m]",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_group_lag{topic=~'platform.sources..*'}) by (group, topic)",
     "legendFormat": "{{topic}}/{{group}}"
    }
   ]
  },
  {
   "title": "Kafka lag (seconds)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_group_lag_seconds{topic=~'platform.sources..*'}) by (group, topic)",
     "legendFormat": "{{topic}}/{{group}}"
    }
   ]
  },
  {
   "title": "Sources API Requests Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(increase(api_3scale_gateway_api_time_bucket{exported_service=\"sources\"}[5m]))",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "Latency Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "sum(increase(api_3scale_gateway_api_time_bucket{exported_service=\"sources\"}[$__interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sources API Requests Count",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Requests / min",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(api_3scale_gateway_api_status{exported_service=\"sources\"}[1m]))",
     "legendFormat": "requests count"
    }
   ]
  },
  {
   "title": "4xx Requests / min",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(api_3scale_gateway_api_status{status=\"4xx\", exported_service=\"sources\"}[1m]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "5xx Requests / min",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(api_3scale_gateway_api_status{status=\"5xx\", exported_service=\"sources\"}[1m]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "CPU & Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "API CPU Usage",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 79 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{container=\"sources-api-svc\"}[1m])) by (pod)",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "API Memory Usage",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 79 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{container=\"sources-api-svc\"}) by (pod)",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Superkey CPU Usage",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 85 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{container=\"sources-superkey-worker-svc\"}[1m])) by (pod)",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Superkey Memory Usage",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 85 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{container=\"sources-superkey-worker-svc\"}) by (pod)",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Satellite CPU Usage",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 91 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{container=\"sources-satellite-operations\"}[1m])) by (pod)",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Satellite Memory Usage",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 91 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{container=\"sources-satellite-operations\"}) by (pod)",
       "legendFormat": "{{ pod }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Satellite Operations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Operations statuses",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 80 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "round(sum(increase(sources_satellite_operations_status_counter[$__range])) by (name, status))",
       "legendFormat": "{{name}} [{{status}}]"
      }
     ]
    },
    {
     "title": "Operation duration",
     "type": "graph",
     "gridPos": { "h": 6, "w": 10, "x": 8, "y": 80 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "rate(sources_satellite_operations_duration_seconds_sum[5m]) / rate(sources_satellite_operations_duration_seconds_count[5m]) * 1000",
       "legendFormat": "{{name}} / {{pod}}"
      }
     ]
    },
    {
     "title": "Operations Errors",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 80 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(sources_satellite_operations_errors_total[$__range])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "RDS Database",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "RDS database connections average",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 84 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(aws_rds_database_connections_average{dbinstance_identifier=\"$namespace\"})",
       "legendFormat": "Connections"
      }
     ]
    },
    {
     "title": "RDS CPU Utilization",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 84 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(aws_rds_cpuutilization_average{dbinstance_identifier=\"$namespace\"})",
       "legendFormat": "CPU utilization average"
      },
      {
       "expr": "sum(rdsosmetrics_cpuUtilization_total{exported_instance=\"$namespace\"})",
       "legendFormat": "OS Metrics Total Util"
      },
      {
       "expr": "sum(rdsosmetrics_cpuUtilization_system{exported_instance=\"$namespace\"})",
       "legendFormat": "OS Metrics System Util"
      }
     ]
    },
    {
     "title": "RDS storage space",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 92 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max(rdsosmetrics_fileSys_total{exported_instance=\"$namespace\", mount_point=\"/rdsdbdata\"})",
       "legendFormat": "Storage total "
      },
      {
       "expr": "max(rdsosmetrics_fileSys_used{exported_instance=\"$namespace\", mount_point=\"/rdsdbdata\"})",
       "legendFormat": "Storage used"
      }
     ]
    },
    {
     "title": "RDS memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 92 },
     "yaxes": [
      { "format": "deckbytes" }
     ],
     "targets": [
      {
       "expr": "max(rdsosmetrics_memory_total{exported_instance=\"$namespace\"})",
       "legendFormat": "Memory total"
      },
      {
       "expr": "max(rdsosmetrics_memory_free{exported_instance=\"$namespace\"})",
       "legendFormat": "Memory free"
      },
      {
       "expr": "max(rdsosmetrics_memory_cached{exported_instance=\"$namespace\"})",
       "legendFormat": "Memory cached"
      },
      {
       "expr": "max(rdsosmetrics_memory_buffers{exported_instance=\"$namespace\"})",
       "legendFormat": "Memory buffers"
      },
      {
       "expr": "max(rdsosmetrics_memory_active{exported_instance=\"$namespace\"})",
       "legendFormat": "Memory active"
      }
     ]
    },
    {
     "title": "RDS tasks",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 100 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max(rdsosmetrics_tasks_sleeping{exported_instance=\"$namespace\"})",
       "legendFormat": "Tasks sleeping"
      },
      {
       "expr": "max(rdsosmetrics_tasks_running{exported_instance=\"$namespace\"})",
       "legendFormat": "Tasks running"
      },
      {
       "expr": "max(rdsosmetrics_tasks_blocked{exported_instance=\"$namespace\"})",
       "legendFormat": "Tasks blocked"
      },
      {
       "expr": "max(rdsosmetrics_tasks_stopped{exported_instance=\"$namespace\"})",
       "legendFormat": "Tasks stopped"
      },
      {
       "expr": "max(rdsosmetrics_tasks_total{exported_instance=\"$namespace\"})",
       "legendFormat": "Tasks total"
      },
      {
       "expr": "max(rdsosmetrics_tasks_zombie{exported_instance=\"$namespace\"})",
       "legendFormat": "Tasks zombie"
      }
     ]
    },
    {
     "title": "RDS DIsk IO util",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 100 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "max(rdsosmetrics_diskIO_util{exported_instance=\"$namespace\"}) by (device)",
       "legendFormat": "Device: {{device}}"
      }
     ]
    },
    {
     "title": "RDS network",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 108 },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "max(rdsosmetrics_network_rx{exported_instance=\"$namespace\"})",
       "legendFormat": "Network receive"
      },
      {
       "expr": "max(rdsosmetrics_network_tx{exported_instance=\"$namespace\"})",
       "legendFormat": "Network transmit"
      }
     ]
    },
    {
     "title": "RDS latency average",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 108 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max(aws_rds_read_latency_average{dbinstance_identifier=\"$namespace\"})",
       "legendFormat": "Read Latency Average"
      },
      {
       "expr": "max(aws_rds_write_latency_average{dbinstance_identifier=\"$namespace\"})",
       "legendFormat": "Write Latency Average"
      }
     ]
    }
   ]
  }
 ]
}