---
apiVersion: v1
kind: Template
metadata:
  name: sources-api-post-deployment-tests
objects:
- apiVersion: cloud.redhat.com/v1alpha1
  kind: ClowdJobInvocation
  metadata:
    name: sources-api-tests-${UID}
  spec:
    appName: sources-api
    testing:
      iqe:
        debug: false
        dynaconfEnvName: stage_post_deploy
        filter: ''
        marker: 'smoke and (not ui)'
parameters:
- name: IMAGE_TAG
  value: ''
  required: true
- name: UID
  description: "Unique CJI name suffix"
  generate: expression
  from: "[a-z0-9]{6}"
